---
version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  labels:
  - automerge
  assignees:
  - javiyt
  reviewers:
  - javiyt
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  labels:
  - automerge
  assignees:
  - javiyt
  reviewers:
  - javiyt
